/* ============================================================
   BANK: Bacteria I · Introduction (PHA3109 Microbiology & Immunology)
   Pure content data — no dependency on shared/ or on the page.
   Question IDs are permanent: never reuse or renumber (BAC1-###).
   This file holds ONLY five things: TOPIC_ID, TOPIC_TITLE,
   CHECKPOINTS, CARDS, POOL. The outline (modules and sections)
   lives in bacteria1.manifest.js.
   ============================================================ */
var TOPIC_ID    = "bacteria1";
var TOPIC_TITLE = "Bacteria I · Introduction";

/* CHECKPOINTS — the short "Can you predict it?" questions inside each
   section. Each one retries until correct. The question wording (stem)
   is written in the page next to the matching data-check id. */
var CHECKPOINTS = {
  c1a: {options:["Prion","Virus","Bacterium","Fungus"], answer:0,
    why:"A prion is acellular and made of protein only, with no DNA or RNA. It spreads by converting normal prion protein (PrP) into a misfolded form. A virus carries DNA or RNA, so it does not fit this description."},
  c1b: {options:["Bacteria and fungi","Fungi and protozoa","Viruses and bacteria","Prions and viruses"], answer:1,
    why:"Fungi and protozoa are both eukaryotes: each has a true, membrane-bound nucleus and 80S ribosomes. Bacteria have a nucleoid and 70S ribosomes, while viruses and prions have no ribosomes at all."},
  c1c: {options:["Binary fission inside a single free-living cell","Templated conversion of normal host protein","Sexual and asexual stages in one or more hosts","Replication using the host cell’s machinery"], answer:2,
    why:"Helminths (worms) use sexual and asexual life-cycle stages, frequently moving between hosts. Binary fission describes bacteria, templated conversion describes prions, and dependence on host machinery describes viruses."},
  c2a: {options:["Little binding, because human cytosolic ribosomes are 80S","Equal binding, because ribosomes are identical in bacteria and humans","Stronger binding, because 80S ribosomes are larger","Binding to the nucleus, because human DNA is packaged with histones"], answer:0,
    why:"The 70S versus 80S size difference is what allows selective toxicity: a drug shaped to fit the bacterial ribosome fits the human cytosolic ribosome poorly, which limits side effects."},
  c2b: {options:["Mitochondrion","Peptidoglycan wall","70S ribosome","Nucleoid"], answer:0,
    why:"Membrane-bound organelles such as mitochondria and lysosomes belong to eukaryotic cells. The peptidoglycan wall, 70S ribosomes, and nucleoid are all bacterial features."},
  c2c: {options:["Peptidoglycan cell wall","70S ribosomes","Division by binary fission","A nucleoid region"], answer:0,
    why:"Mycoplasma is a bacterium that lacks a cell wall. That is why the peptidoglycan column of the comparison table carries an asterisk, and why wall-targeting drugs miss it."},
  c3a: {options:["Staphylococci","Diplococci","Streptococci","Spirochetes"], answer:2,
    why:"The prefix strepto- means chains. Round cells that stay attached after dividing, forming a chain, are streptococci. Staphylo- means clusters and diplo- means pairs."},
  c3b: {options:["Capsule","Flagellum","Plasmid","Cell wall"], answer:3,
    why:"Shape is dictated by the characteristics of the cell wall, which is why shape is a useful identification criterion. The capsule sits outside the wall, and flagella and plasmids do not set cell shape."},
  c4a: {options:["Slime layer","Capsule","Pilus","Flagellum"], answer:1,
    why:"A capsule is an organized glycocalyx that is tightly attached to the cell wall. A slime layer is diffuse and loosely attached, so it protects less effectively against phagocytosis."},
  c4b: {options:["Weaker attachment to host surfaces","Loss of the ability to swim","A thinner peptidoglycan cell wall","Loss of the 70S ribosomes in the cell"], answer:0,
    why:"Pili attach to the cell membrane and are used for adhesion. Motility belongs to flagella, so losing pili mainly weakens attachment."},
  c4c: {options:["Antigens for bacterial vaccines","Binding sites for macrolides","Targets for beta-lactam drugs","Substrates for catalase"], answer:0,
    why:"Capsule polysaccharides are displayed on the surface, so the immune system can recognize them. That makes them useful antigens in bacterial vaccines."},
  c5a: {options:["Synthesis of the NAG and NAM sugars","Peptide cross-linking (transpeptidation)","Assembly of the outer membrane layer","Attachment of teichoic acids to the wall"], answer:1,
    why:"Beta-lactams block the transpeptidation step that cross-links glycan chains through their peptide bridges. Without cross-links the wall loses its strength."},
  c5b: {options:["The cell swells and bursts (lysis)","The cell builds an outer membrane","The cell converts to a spore","The cell divides faster"], answer:0,
    why:"Peptidoglycan cross-links give the wall the strength to resist internal pressure. When cross-linking is blocked in a growing cell, the weakened wall gives way and the cell lyses."},
  c6a: {options:["Inner membrane, thick peptidoglycan with teichoic acids","Inner membrane, thin peptidoglycan, outer membrane with LPS","Outer membrane, thin peptidoglycan, inner membrane","Inner membrane, outer membrane, thick peptidoglycan"], answer:1,
    why:"Reading from the inside out, a Gram-negative envelope has the inner (cytoplasmic) membrane, a thin peptidoglycan layer in the periplasm, and then the outer membrane carrying lipopolysaccharide. The first option describes a Gram-positive envelope."},
  c6b: {options:["Outer membrane","Teichoic acid layer","Thick peptidoglycan","Pilus"], answer:0,
    why:"The outer membrane is a permeability barrier. Porins admit small hydrophilic molecules, but a large hydrophilic drug is largely kept out, which is a form of intrinsic resistance."},
  c6c: {options:["Lipopolysaccharide","Porins","Teichoic acids","Mycolic acids"], answer:2,
    why:"Teichoic acids are embedded in the thick peptidoglycan of Gram-positive bacteria. LPS and porins belong to the Gram-negative outer membrane, and mycolic acids belong to Mycobacterium."},
  c7a: {options:["Gram-positive cells, because of their thick peptidoglycan","Gram-negative cells, because of their outer membrane","Gram-negative cells, because of their thin peptidoglycan","Gram-positive cells, because of their lipopolysaccharide"], answer:0,
    why:"During decolorization the crystal violet–iodine complex stays trapped inside the thick peptidoglycan of Gram-positive cells. Gram-negative cells lose it. LPS is a Gram-negative component, so the last option mixes the groups."},
  c7b: {options:["Purple","Pink","Colorless","Orange"], answer:2,
    why:"The alcohol wash removes the crystal violet–iodine complex from Gram-negative cells, leaving them colorless until safranin stains them pink. Pink appears only after the counterstain step."},
  c8a: {options:["Strongly purple, because of a thick wall","Pink, because of an outer membrane","Poorly stained and unreliable to interpret","Purple, because of teichoic acids"], answer:2,
    why:"Mycoplasma lacks a cell wall and is very small, so the Gram stain is not a reliable way to classify it. It is the prototype organism for this problem."},
  c8b: {options:["Dark-field microscopy","Acid-fast stain","Extended safranin time","Giemsa stain"], answer:1,
    why:"Mycobacteria have a lipid-rich, mycolic acid outer layer that resists Gram dyes. The acid-fast stain is the alternative approach. Dark-field suits Treponema, extended counterstain suits Legionella, and Giemsa suits Rickettsiae."},
  c9a: {options:["High, because the target is absent from the patient","Low, because human cells depend on a similar wall","Low, because bacteria and humans share ribosomes","High, because human cells are bigger than bacteria"], answer:0,
    why:"Selective toxicity is highest when the drug’s target exists in the microbe and has no counterpart in the patient. Human cells make no peptidoglycan, so wall-synthesis inhibitors have a wide safety margin."},
  c9b: {options:["Beta-lactams","Macrolides","Fluoroquinolones","Sulfonamides"], answer:1,
    why:"Macrolides, tetracyclines, and aminoglycosides bind the bacterial 70S ribosome. Beta-lactams target peptidoglycan, fluoroquinolones target DNA gyrase, and sulfonamides target folate synthesis."},
  c9c: {options:["Macrolides and tetracyclines","Sulfonamides and trimethoprim","Fluoroquinolones and beta-lactams","Daptomycin and polymyxins"], answer:1,
    why:"Bacteria synthesize their own folate, while humans obtain it from the diet. Sulfonamides and trimethoprim block steps of bacterial folate synthesis, so they exploit that difference."},
  c10a: {options:["At the surface of the tube","At the bottom of the tube","Evenly throughout the tube","In a band just below the surface"], answer:0,
    why:"An obligate aerobe needs oxygen, and oxygen is highest at the surface. A band just below the surface is the pattern of a microaerophile, which needs low oxygen."},
  c10b: {options:["Obligate anaerobe","Facultative anaerobe","Aerotolerant anaerobe","Microaerophile"], answer:1,
    why:"A facultative anaerobe grows better with oxygen, since aerobic growth gives a higher yield, but it can also grow without it. An aerotolerant anaerobe grows evenly throughout because it does not use oxygen."},
  c10c: {options:["Coagulase and collagenase","Transpeptidase and gyrase","Superoxide dismutase and catalase","Lipase and protease"], answer:2,
    why:"Aerobic growth generates reactive oxygen species (ROS). Superoxide dismutase and catalase neutralize them, so organisms that grow with oxygen typically carry both."},
  c11a: {options:["An alcohol-based surface wipe","A sporicidal bleach-based disinfectant","A rinse of the surfaces with plain water","Air-drying the room after cleaning"], answer:1,
    why:"Endospores resist alcohol, drying, and many disinfectants. Environmental cleaning for C. difficile precautions needs a sporicidal agent such as dilute bleach."},
  c11b: {options:["Reproduction that turns one cell into many","Survival of harsh conditions, one spore per cell","Transfer of plasmid DNA to a neighboring cell","Delivery of toxin into the cytoplasm of host cells"], answer:1,
    why:"Endospores are dormant survival structures, not reproductive ones. A single vegetative cell forms a single spore, so sporulation does not increase cell numbers."},
  c12a: {options:["Transformation","Transduction","Conjugation","Mutation"], answer:2,
    why:"Conjugation is direct cell-to-cell transfer through physical contact, with a pilus forming the bridge. Plasmids are the usual cargo, which is why it spreads resistance so effectively."},
  c12b: {options:["Conjugation","Transformation","Transduction","Transposition"], answer:1,
    why:"Transformation is uptake of naked (free) DNA from the environment, for example DNA released from a dead cell. It needs neither cell contact nor a virus."},
  c12c: {options:["Bacteriophage","Pilus","Endospore","Transposon"], answer:3,
    why:"Transposons move DNA from place to place within a bacterial genome, between the chromosome and plasmids. A bacteriophage moves DNA between cells, and a pilus forms the bridge for conjugation."},
  c13a: {options:["Intrinsic resistance","Acquired resistance by mutation","Acquired resistance by conjugation","Acquired resistance by transformation"], answer:0,
    why:"Intrinsic resistance is an inherent property of the organism, such as outer-membrane impermeability in Gram-negative bacteria. Acquired resistance arises later, through mutation or horizontal gene transfer."},
  c13b: {options:["The drug creates resistance mutations in the survivors","Resistant survivors multiply as susceptible cells die","Resistant cells convert into dormant endospores","Susceptible cells transform into resistant ones"], answer:1,
    why:"Antimicrobial exposure selects for resistant subpopulations that were already present. The drug does not create the mutation; it removes the competition so resistant survivors can proliferate."},
  c14a: {options:["Skin","Colon","Lower airways","Healthy bladder"], answer:1,
    why:"The colon holds most of the human microbiome, a dense and mostly anaerobic community. The lower airways and healthy bladder are low-biomass environments."},
  c14b: {options:["Weaker, since fewer resident microbes compete with pathogens","Stronger, since the antibiotic remains active in the gut","Unchanged, since the immune system replaces the microbiota","Stronger, since pathogens die along with resident microbes"], answer:0,
    why:"Colonization resistance depends on resident microbes competing for adhesion sites and nutrients, making antimicrobial metabolites, and stimulating host defenses. Depleting them opens the door to pathogens such as C. difficile."},
  c14c: {options:["Forming endospores","Producing a low pH","Secreting collagenase","Making a capsule"], answer:1,
    why:"Vaginal Lactobacillus species maintain a low pH that limits pathogen growth. It is a clear example of the microbiota shaping its own environment."},
  c15a: {options:["Contamination","Colonization","Infection","Disease"], answer:1,
    why:"Colonization is presence or growth of an organism without attributable tissue injury or disease. Infection would need tissue invasion and a host response."},
  c15b: {options:["Contamination","Colonization","Infection","Latent infection"], answer:0,
    why:"Contamination means the organism came from an external source, such as specimen handling, and was never growing in the patient. That is why it is a distinct idea from colonization."},
  c16a: {options:["Vector","Reservoir","Fomite","Zoonosis"], answer:2,
    why:"A fomite is an inanimate object that transfers microbes, such as a doorknob, towel, or bedsheet. A vector is a living organism, usually an arthropod."},
  c16b: {options:["Reservoir","Source","Vector","Fomite"], answer:1,
    why:"The source is the immediate origin of a particular exposure and may differ from the reservoir, which is the normal habitat that maintains and multiplies the agent."},
  c17a: {options:["More susceptible, because crowded cells share antibiotics","Equally susceptible, because the MIC is unchanged","Less susceptible, because the matrix limits drug penetration","More susceptible, because the device attracts drug"], answer:2,
    why:"A biofilm’s protective matrix of proteins, polysaccharides, and extracellular DNA reduces antibiotic penetration, so bacteria inside are tolerant even when the same organism tests susceptible in the lab."},
  c17b: {options:["Coagulase","Hyaluronidase","Collagenase","IgA protease"], answer:0,
    why:"Coagulase promotes fibrin clot formation that can wall bacteria off from phagocytes. Hyaluronidase and collagenase help bacteria spread, and IgA protease cleaves secretory IgA."},
  c17c: {options:["Coagulase","Leukocidin","Capsule","Hyaluronidase"], answer:1,
    why:"Leukocidins are pore-forming toxins that destroy neutrophils and macrophages, for example those produced by S. aureus. A capsule blocks phagocytes from attaching but does not form pores."},
  c18a: {options:["Exotoxin","Endotoxin","Teichoic acid","Lipid A"], answer:0,
    why:"Exotoxins are secreted polypeptides. Treating them with formaldehyde produces toxoids, which are used in vaccines. Endotoxin (LPS) is weakly antigenic and is not used to form toxoids."},
  c18b: {options:["Lipid A","Core oligosaccharide","O antigen","Teichoic acid"], answer:0,
    why:"LPS is built from lipid A, a core oligosaccharide, and the O antigen, in that order outward from the membrane. Lipid A is the major inflammatory component."},
  c18c: {options:["Direct tissue destruction by a secreted exotoxin","The host immune response reacting with host tissue","A biofilm forming on the surface of heart valves","Endotoxin released by dying Gram-negative rods"], answer:1,
    why:"In rheumatic fever, immune responses against S. pyogenes antigens, including molecular mimicry involving the M protein, injure host tissue. The damage comes from the host response rather than from the organism itself."},
  c19a: {options:["Susceptibility testing","Organism identification","Specimen quality","Gram stain"], answer:2,
    why:"A well-collected specimen from the right site is the foundation for every downstream result. A poor specimen produces misleading Gram stains, cultures, and susceptibility reports."},
  c19b: {options:["The exact species and the MIC of each drug","Shape and Gram reaction to guide empiric therapy","Whether the organism is causing infection","Which plasmids the organism is carrying"], answer:1,
    why:"A Gram stain reports shape, size, arrangement, and Gram reaction, which helps choose initial (empiric) therapy while cultures incubate. It cannot give the species, susceptibility, or clinical significance."},
  c21a: {options:["Interpret the result with the patient’s symptoms","Begin treatment based on the culture result alone","Discard the result as a probable laboratory error","Repeat the culture on a different agar plate"], answer:0,
    why:"A few colonies of S. pneumoniae from a mildly ill outpatient’s sputum can reflect upper-airway colonization or contamination. Culture results have to be read alongside the clinical picture."},
  c21b: {options:["Colonization of the meninges by normal flora","Contamination from the skin during collection","A true pathogen, since CSF is normally sterile","A resident member of the normal flora"], answer:2,
    why:"Cerebrospinal fluid is normally sterile, so growth of Neisseria meningitidis from it should be treated as a true pathogen rather than as a colonizer."},
  c22a: {options:["The lowest concentration that visibly inhibits growth","The lowest concentration that kills the organism","The highest dose that is safe for the patient","The concentration reached in the patient’s blood"], answer:0,
    why:"The minimum inhibitory concentration (MIC) is the lowest antimicrobial concentration that visibly inhibits growth in the laboratory. It describes the organism in a test tube, not the drug level in a patient."},
  c22b: {options:["Resistant (R)","Susceptible (S)","Intermediate (I)"], answer:1,
    why:"Susceptible means the organism is likely to respond to standard dosing. Intermediate may respond at higher dosing or where the drug concentrates, and resistant is unlikely to respond even at maximal safe dosing."},
  c22c: {options:["The laboratory measured the MIC incorrectly for this isolate","The MIC is measured in a test tube, apart from biofilm and drug penetration","Susceptible organisms convert to resistant ones inside the patient","Antibiotics become inactive once a device is implanted"], answer:1,
    why:"MIC and susceptibility results describe the organism in a test tube. They do not account for biofilms, source control, or how much drug actually reaches the infection site."}
};

/* CARDS — flashcards (Retrieval Practice). */
var CARDS = [
  {"id":"BAC1-CARD-01","t":"Prion","d":"Acellular, protein-only infectious agent with no nucleic acid. Spreads by templated conversion of normal prion protein (PrP) into a misfolded form."},
  {"id":"BAC1-CARD-02","t":"Virus","d":"Acellular agent containing DNA or RNA (not both). Replicates only by using host-cell machinery; has no ribosomes."},
  {"id":"BAC1-CARD-03","t":"Bacterium (prokaryote)","d":"Cellular organism with a nucleoid rather than a membrane-bound nucleus, 70S ribosomes, and (usually) a peptidoglycan wall. Divides by binary fission."},
  {"id":"BAC1-CARD-04","t":"Fungus","d":"Eukaryote with a chitin-containing wall and 80S ribosomes. Uni- or multicellular; reproduces by budding or mitosis."},
  {"id":"BAC1-CARD-05","t":"What differs between a bacterial and a human cell?","d":"Bacteria: no nuclear membrane, no organelles, 70S ribosomes, peptidoglycan wall. Humans: nucleus, organelles, 80S cytosolic ribosomes, no peptidoglycan. These differences guide therapy and predict side effects."},
  {"id":"BAC1-CARD-06","t":"Coccus, bacillus, spirochete","d":"Sphere, rod, and spiral. Shape is set by the cell wall and is an identification criterion."},
  {"id":"BAC1-CARD-07","t":"Diplo-, strepto-, staphylo-","d":"Arrangement after division: pairs, chains, and clusters."},
  {"id":"BAC1-CARD-08","t":"Glycocalyx","d":"Broad term for the polymer layer outside the cell wall. A capsule is organized and tightly attached; a slime layer is diffuse and loosely attached."},
  {"id":"BAC1-CARD-09","t":"Pili and flagella","d":"Pili are used for adhesion (and conjugation); flagella provide motility."},
  {"id":"BAC1-CARD-10","t":"Peptidoglycan","d":"Polymer of alternating NAG and NAM sugars cross-linked by short peptide bridges. Unique to bacteria, so it is an ideal selective target."},
  {"id":"BAC1-CARD-11","t":"Transpeptidation","d":"The cross-linking step of peptidoglycan synthesis. Beta-lactam antibiotics block it, weakening the wall."},
  {"id":"BAC1-CARD-12","t":"Gram-positive envelope","d":"Cytoplasmic membrane plus a thick peptidoglycan wall that contains teichoic acids."},
  {"id":"BAC1-CARD-13","t":"Gram-negative envelope","d":"Inner membrane, a thin peptidoglycan layer in the periplasm, and an outer membrane carrying LPS and porins."},
  {"id":"BAC1-CARD-14","t":"Porins","d":"Channels in the Gram-negative outer membrane that let small hydrophilic molecules (sugars, amino acids, some drugs) cross."},
  {"id":"BAC1-CARD-15","t":"Gram stain steps","d":"Crystal violet (primary stain) → iodine (mordant) → alcohol (decolorizer) → safranin (counterstain). Gram-positive: purple. Gram-negative: pink."},
  {"id":"BAC1-CARD-16","t":"Why some bacteria fail the Gram stain","d":"Mycobacterium: lipid-rich mycolic acids (use acid-fast). Treponema: too thin (dark-field). Mycoplasma: no wall. Legionella: poor counterstain uptake. Chlamydiae and Rickettsiae: obligate intracellular and small."},
  {"id":"BAC1-CARD-17","t":"Selective toxicity","d":"Harming the microbe without harming the patient, by targeting something the microbe has and the patient lacks."},
  {"id":"BAC1-CARD-18","t":"Five selective targets","d":"Peptidoglycan; 70S ribosomes; folate synthesis; DNA gyrase/topoisomerase; bacterial membranes."},
  {"id":"BAC1-CARD-19","t":"Obligate aerobe / obligate anaerobe","d":"Aerobe: requires oxygen (grows at the surface). Anaerobe: oxygen inhibits or kills it (grows at the bottom)."},
  {"id":"BAC1-CARD-20","t":"Facultative anaerobe","d":"Uses oxygen when available but can also grow without it (for example E. coli). Aerobic growth gives a higher yield."},
  {"id":"BAC1-CARD-21","t":"Microaerophile vs. aerotolerant anaerobe","d":"Microaerophile needs low oxygen. Aerotolerant anaerobe tolerates oxygen but does not use it for growth."},
  {"id":"BAC1-CARD-22","t":"Superoxide dismutase and catalase","d":"Enzymes that neutralize reactive oxygen species. Aerobic growth requires them."},
  {"id":"BAC1-CARD-23","t":"Obligate intracellular pathogen","d":"Requires living host cells to grow. Examples: Chlamydia, Rickettsia, Ehrlichia, Anaplasma."},
  {"id":"BAC1-CARD-24","t":"Endospore","d":"Dormant survival structure (one per cell, so cell numbers do not rise). Resists heat, drying, radiation, and many disinfectants. Key genera: Clostridioides and Bacillus."},
  {"id":"BAC1-CARD-25","t":"C. difficile precautions","d":"Soap-and-water hand washing (alcohol rub does not kill spores) plus sporicidal disinfectant such as dilute bleach for surfaces."},
  {"id":"BAC1-CARD-26","t":"Transformation, transduction, conjugation","d":"Uptake of naked DNA; DNA carried by a bacteriophage; direct cell-to-cell transfer through a pilus bridge."},
  {"id":"BAC1-CARD-27","t":"Plasmid","d":"Circular DNA construct that can encode resistance, virulence, metabolic, and transfer traits. The usual cargo in conjugation."},
  {"id":"BAC1-CARD-28","t":"Intrinsic vs. acquired resistance","d":"Intrinsic: inherent property (for example outer-membrane impermeability). Acquired: gained through mutation or horizontal gene transfer."},
  {"id":"BAC1-CARD-29","t":"How resistance spreads","d":"Drug exposure selects resistant survivors, they proliferate without competition, and they can pass genes to other bacteria."},
  {"id":"BAC1-CARD-30","t":"Colonization resistance","d":"The resident microbiota limits pathogen colonization by competing for adhesion sites and nutrients, making antimicrobial metabolites and bacteriocins, and stimulating host defenses."},
  {"id":"BAC1-CARD-31","t":"Colonization vs. contamination","d":"Colonization: organism present or growing without tissue injury. Contamination: organism from an external source that was never growing in the patient."},
  {"id":"BAC1-CARD-32","t":"Infection vs. disease","d":"Infection: tissue invaded and host response occurring, with or without symptoms. Disease: symptomatic illness resulting from infection."},
  {"id":"BAC1-CARD-33","t":"Fomite","d":"Inanimate object that transfers microbes, such as a doorknob, towel, or bedsheet."},
  {"id":"BAC1-CARD-34","t":"Reservoir vs. source","d":"Reservoir: the normal habitat that maintains and multiplies the agent. Source: the immediate origin of a particular exposure (may differ)."},
  {"id":"BAC1-CARD-35","t":"Vector and zoonosis","d":"Vector: living organism, usually an arthropod, that transmits an agent. Zoonosis: disease that uses animals as reservoirs."},
  {"id":"BAC1-CARD-36","t":"Pathogenicity vs. virulence","d":"Pathogenicity: ability to cause disease. Virulence: the degree of that ability, arising from virulence factors."},
  {"id":"BAC1-CARD-37","t":"Biofilm","d":"Protective matrix of proteins, polysaccharides, and extracellular DNA that forms after adherence, often on implanted devices. Cells inside tolerate antibiotics."},
  {"id":"BAC1-CARD-38","t":"Tissue-spreading and evasion factors","d":"Collagenase and hyaluronidase spread; coagulase builds a fibrin barrier; IgA protease cleaves secretory IgA; capsule, M protein, and protein A block opsonization; leukocidins destroy phagocytes."},
  {"id":"BAC1-CARD-39","t":"Opsonization","d":"Antibody or complement C3b coats a pathogen to mark it for phagocytosis."},
  {"id":"BAC1-CARD-40","t":"Exotoxin vs. endotoxin","d":"Exotoxin: secreted polypeptide, potent, can be made into toxoids. Endotoxin: LPS of the Gram-negative outer membrane; lipid A drives fever and shock."},
  {"id":"BAC1-CARD-41","t":"LPS structure","d":"Lipid A (major inflammatory part) – core oligosaccharide – O antigen, in that order outward from the membrane."},
  {"id":"BAC1-CARD-42","t":"Immunopathogenesis","d":"Disease produced by the host’s immune response rather than by the organism itself, such as rheumatic fever after S. pyogenes."},
  {"id":"BAC1-CARD-43","t":"Diagnostic sequence","d":"Specimen quality → Gram stain → culture or NAAT/antigen → identification → susceptibility → clinical interpretation."},
  {"id":"BAC1-CARD-44","t":"What a Gram stain can and cannot tell you","d":"It gives shape, size, arrangement, and Gram reaction to guide empiric therapy. It cannot give the species, susceptibility, or whether the organism is causing infection."},
  {"id":"BAC1-CARD-45","t":"MIC","d":"Minimum inhibitory concentration: the lowest antimicrobial concentration that visibly inhibits growth in the laboratory."},
  {"id":"BAC1-CARD-46","t":"S, I, and R","d":"Susceptible: likely to respond to standard dosing. Intermediate: may respond at higher dosing or where the drug concentrates. Resistant: unlikely to respond even at maximal safe dosing."},
  {"id":"BAC1-CARD-47","t":"Detection ≠ infection ≠ antibiotic","d":"Finding an organism does not by itself establish infection, and infection is not automatically an indication for an antibiotic. Interpret with the clinical picture."}
];

/* POOL — practice questions. Feeds the five module quizzes, the
   adaptive "practice what you missed" rounds, and the Mastery Exam.
   m = module, area = concept area (must match a key in areaSection
   in the manifest), level = concept | application | integration. */
var POOL = [

  /* ----- Module 1 ----- */
  {id:"BAC1-001", m:"m1", area:"Microbial categories", level:"concept",
   stem:"Which structure do bacteria, fungi, and protozoa share that viruses lack?",
   options:["Ribosomes","A nucleus","A peptidoglycan wall","A chitin wall"], answer:0,
   why:"Bacteria have 70S ribosomes and fungi and protozoa have 80S ribosomes, while viruses have none and depend on host machinery. A nucleus belongs only to the eukaryotes, and peptidoglycan and chitin are wall components of bacteria and fungi respectively."},
  {id:"BAC1-002", m:"m1", area:"Microbial categories", level:"concept",
   stem:"Which process describes how bacteria replicate?",
   options:["Budding and mitosis","Binary fission","Templated conversion","Replication within a host cell"], answer:1,
   why:"Bacteria divide by binary fission. Budding and mitosis describe fungi, templated conversion describes prions, and replication within host cells describes viruses."},
  {id:"BAC1-003", m:"m1", area:"Microbial categories", level:"application",
   stem:"A lab report describes an isolate with a chitin-containing wall, 80S ribosomes, and a membrane-bound nucleus. Which category fits?",
   options:["Bacterium","Virus","Fungus","Prion"], answer:2,
   why:"A chitin wall, 80S ribosomes, and a true nucleus together identify a fungus. A bacterium would show 70S ribosomes and a nucleoid, and viruses and prions have no ribosomes."},
  {id:"BAC1-004", m:"m1", area:"Microbial categories", level:"application",
   stem:"An agent contains RNA, lacks ribosomes, and replicates using a host cell’s machinery. Which category fits?",
   options:["Bacterium","Protozoan","Prion","Virus"], answer:3,
   why:"Viruses are acellular, carry either DNA or RNA, and use host machinery to replicate. A prion contains no nucleic acid at all."},
  {id:"BAC1-005", m:"m1", area:"Bacteria vs. human cells", level:"concept",
   stem:"Which description fits the chromosome of a bacterial cell such as E. coli?",
   options:["Packaged into nucleosomes with histones","A single circular molecule in a nucleoid","Divided among several linear chromosomes","Enclosed by a nuclear membrane"], answer:1,
   why:"A bacterial chromosome is usually a single circular molecule lying in the nucleoid, without a nuclear membrane or histone-based nucleosomes. Some bacteria carry more than one chromosome, so the single circle is a strong tendency rather than a rule."},
  {id:"BAC1-006", m:"m1", area:"Bacteria vs. human cells", level:"concept",
   stem:"Which pairing matches ribosome sizes in bacteria and in the cytosol of human cells?",
   options:["Bacteria 80S, human 70S","Bacteria 70S, human 80S","Bacteria 70S, human 70S","Bacteria 80S, human 80S"], answer:1,
   why:"Bacteria have 70S ribosomes and human cytosolic ribosomes are 80S. The size difference is the basis for ribosome-targeting antibiotics."},
  {id:"BAC1-007", m:"m1", area:"Bacteria vs. human cells", level:"application",
   stem:"Which structural difference best explains why penicillin-class drugs leave human cells largely unaffected?",
   options:["Human cells lack a peptidoglycan wall","Human cells have larger ribosomes","Human cells divide by mitosis","Human cells package DNA with histones"], answer:0,
   why:"Penicillin-class drugs (beta-lactams) block peptidoglycan cross-linking. Human cells build no peptidoglycan, so the target is missing. The other differences are true but unrelated to this drug’s target."},
  {id:"BAC1-008", m:"m1", area:"Bacteria vs. human cells", level:"integration",
   stem:"A drug that blocks peptidoglycan cross-linking is under study. Which pathogen is a plausible target?",
   options:["Candida albicans","Influenza virus","Staphylococcus aureus","Plasmodium falciparum"], answer:2,
   why:"Peptidoglycan is a bacterial polymer. Candida is a fungus with a chitin wall, influenza is an acellular virus, and Plasmodium is a eukaryotic protozoan, so none of them builds the target."},
  {id:"BAC1-009", m:"m1", area:"Shape and arrangement", level:"concept",
   stem:"Which prefix describes cells arranged in clusters after division?",
   options:["Diplo-","Strepto-","Staphylo-","Pleo-"], answer:2,
   why:"Staphylo- means clusters, strepto- means chains, and diplo- means pairs. Pleomorphic refers to variable shape rather than arrangement."},
  {id:"BAC1-010", m:"m1", area:"Shape and arrangement", level:"application",
   stem:"Rod-shaped cells joined end to end in a chain are best described by which term?",
   options:["Diplococci","Streptobacilli","Staphylococci","Spirochetes"], answer:1,
   why:"Bacillus refers to a rod and strepto- to a chain, so chained rods are streptobacilli. Diplococci and staphylococci describe spheres, and spirochetes are spiral."},
  {id:"BAC1-011", m:"m1", area:"Shape and arrangement", level:"concept",
   stem:"Which observation supports calling an organism pleomorphic?",
   options:["Cells joined together in irregular clusters","Cells sharing a uniform spiral form","Cells forming dormant survival spores","Cells of variable shape within one culture"], answer:3,
   why:"Pleomorphic bacteria exhibit variable shapes. Clusters describe an arrangement, a spiral is the spirochete shape, and spore formation is a separate survival trait."},
  {id:"BAC1-012", m:"m1", area:"Bacterial structures", level:"concept",
   stem:"Which term is the broad name for the polymer layer outside the bacterial cell wall?",
   options:["Periplasm","Glycocalyx","Nucleoid","Cytoplasmic membrane"], answer:1,
   why:"Glycocalyx is the broad term for the layer outside the wall. A capsule is the organized, tightly attached form, and a slime layer is the diffuse, loosely attached form."},
  {id:"BAC1-013", m:"m1", area:"Bacterial structures", level:"concept",
   stem:"Which structure gives a bacterium the ability to swim?",
   options:["Pilus","Capsule","Flagellum","Plasmid"], answer:2,
   why:"Flagella provide motility. Pili are used for adhesion, and capsules and plasmids do not power movement."},
  {id:"BAC1-014", m:"m1", area:"Bacterial structures", level:"integration",
   stem:"A bacterium on an implanted catheter resists phagocytes. Which two glycocalyx functions does this scenario illustrate?",
   options:["Motility and transfer of DNA to neighbors","Toxin secretion and formation of spores","Surface adhesion and protection from phagocytosis","Protein synthesis and energy production"], answer:2,
   why:"The glycocalyx helps bacteria attach to surfaces such as implants and protects them from phagocytosis, desiccation, and toxins. Motility, toxin secretion, and protein synthesis are handled by other structures."},

  /* ----- Module 2 ----- */
  {id:"BAC1-015", m:"m2", area:"Peptidoglycan", level:"concept",
   stem:"Which two sugars alternate in the glycan chains of peptidoglycan?",
   options:["Glucose and fructose in a repeating disaccharide","N-acetylglucosamine and a lipid A sugar","N-acetylmuramic acid and teichoic acid","N-acetylglucosamine and N-acetylmuramic acid"], answer:3,
   why:"The glycan chains alternate NAG (N-acetylglucosamine) and NAM (N-acetylmuramic acid), joined by β-1,4 glycosidic bonds. Lipid A and teichoic acid are separate envelope components."},
  {id:"BAC1-016", m:"m2", area:"Peptidoglycan", level:"concept",
   stem:"In peptidoglycan, short peptide bridges connect which components?",
   options:["The outer membrane and the capsule","Adjacent glycan chains","The two strands of DNA","Ribosomal subunits"], answer:1,
   why:"Peptide bridges of about four to five amino acids cross-link neighboring glycan chains, forming the strong mesh of the wall."},
  {id:"BAC1-017", m:"m2", area:"Peptidoglycan", level:"application",
   stem:"A bacterium is exposed to a drug that blocks transpeptidation. Which change in the wall is expected?",
   options:["A thicker layer of teichoic acids in the wall","Loss of the outer membrane from the envelope","Loss of the cytoplasmic membrane below the wall","Fewer peptide cross-links, so a weaker wall"], answer:3,
   why:"Transpeptidation forms the peptide cross-links. Blocking it leaves fewer links between glycan chains and a wall that cannot withstand internal pressure."},
  {id:"BAC1-018", m:"m2", area:"Peptidoglycan", level:"integration",
   stem:"A pharmacist explains that beta-lactams injure dividing bacteria yet spare human cells. Which statement gives the reason?",
   options:["They block cross-linking, a step specific to bacteria","They bind 80S ribosomes, a structure absent from bacteria","They block the uptake of folate from the human diet","They selectively dissolve the human plasma membrane"], answer:0,
   why:"Beta-lactams block the transpeptidation step of peptidoglycan synthesis. Peptidoglycan is unique to bacteria, which gives the drugs their selective toxicity."},
  {id:"BAC1-019", m:"m2", area:"Envelope architecture", level:"concept",
   stem:"Which structure distinguishes a Gram-negative envelope from a Gram-positive one?",
   options:["A thick peptidoglycan layer","A layer of teichoic acids","A cytoplasmic (inner) membrane","An outer membrane containing LPS"], answer:3,
   why:"Gram-negative bacteria add an outer membrane containing lipopolysaccharide over a thin peptidoglycan layer. Both groups have a cytoplasmic membrane, and thick peptidoglycan with teichoic acids marks Gram-positive cells."},
  {id:"BAC1-020", m:"m2", area:"Envelope architecture", level:"application",
   stem:"An engineered Gram-negative bacterium loses its outer membrane. Which change in drug entry is expected?",
   options:["Harder entry of small hydrophilic drugs","Gain of a thicker teichoic acid layer","Loss of the peptidoglycan layer","Easier entry of large hydrophilic drugs"], answer:3,
   why:"The outer membrane restricts large hydrophilic molecules, and porins admit only small hydrophilic ones. Removing the barrier lets large hydrophilic drugs reach the wall and membrane more easily."},
  {id:"BAC1-021", m:"m2", area:"Envelope architecture", level:"concept",
   stem:"A prominent periplasm between an inner and an outer membrane is associated with which group?",
   options:["Gram-positive bacteria","Fungi with chitin walls","Gram-negative bacteria","Mycoplasma species"], answer:2,
   why:"Gram-negative bacteria have a prominent periplasm between the inner and outer membranes. Gram-positive bacteria have no outer-membrane-defined periplasm, and Mycoplasma lacks a cell wall."},
  {id:"BAC1-022", m:"m2", area:"Envelope architecture", level:"application",
   stem:"A large glycopeptide antibiotic is active against Gram-positive cocci but weak against Gram-negative rods. Which structure best explains the difference?",
   options:["Outer membrane","Teichoic acids","Cytoplasmic membrane","Flagellum"], answer:0,
   why:"Glycopeptides target peptidoglycan, which both groups make. The Gram-negative outer membrane keeps large hydrophilic molecules from reaching it, which explains the weaker activity."},
  {id:"BAC1-023", m:"m2", area:"Gram staining", level:"concept",
   stem:"Which order lists the Gram stain reagents correctly?",
   options:["Safranin, iodine, alcohol, crystal violet","Crystal violet, alcohol, iodine, safranin","Iodine, crystal violet, safranin, alcohol","Crystal violet, iodine, alcohol, safranin"], answer:3,
   why:"Crystal violet is the primary stain, iodine is the mordant that forms the complex, alcohol decolorizes, and safranin counterstains."},
  {id:"BAC1-024", m:"m2", area:"Gram staining", level:"application",
   stem:"A Gram stain of a specimen shows pink rods. Which conclusion is supported?",
   options:["The organism is E. coli, a Gram-negative rod","The cells are fungal yeast forms","The cells are Gram-negative rods of unknown species","The cells are Gram-positive rods of unknown species"], answer:2,
   why:"Pink means the cells lost the crystal violet–iodine complex and took up safranin, so they are Gram-negative. The rod shape adds morphology, but a Gram stain cannot name the species."},
  {id:"BAC1-025", m:"m2", area:"Gram staining", level:"application",
   stem:"Which pairing of stain result and structural explanation is correct?",
   options:["Pink: thick peptidoglycan retains the dye","Purple: the outer membrane retains the dye","Purple: thick peptidoglycan retains the dye","Pink: teichoic acids retain the dye"], answer:2,
   why:"Gram-positive cells stay purple because their thick peptidoglycan retains the crystal violet–iodine complex. Gram-negative cells lose it and appear pink after safranin."},
  {id:"BAC1-026", m:"m2", area:"Gram stain exceptions", level:"concept",
   stem:"Which genus has an outer layer rich in mycolic acids?",
   options:["Treponema","Legionella","Mycobacterium","Mycoplasma"], answer:2,
   why:"Mycobacterium has a unique, lipid-rich outer layer of mycolic acids that blocks Gram dyes. It is identified with an acid-fast stain instead."},
  {id:"BAC1-027", m:"m2", area:"Gram stain exceptions", level:"application",
   stem:"Treponema pallidum is too thin to see after Gram staining. Which technique visualizes it?",
   options:["Acid-fast stain","Dark-field microscopy","Extended counterstain time","Inclusion body staining"], answer:1,
   why:"Dark-field microscopy or a fluorescent antibody reveals Treponema. Acid-fast staining is for mycobacteria, extended counterstain time is for Legionella, and inclusion bodies are used for Chlamydiae."},
  {id:"BAC1-028", m:"m2", area:"Gram stain exceptions", level:"application",
   stem:"Which explanation fits the Gram-stain limitation of Chlamydiae?",
   options:["Excess lipid in the cell wall blocks the dye","Poor uptake of the red counterstain","A spiral body too thin to be seen","Obligate intracellular life and very small size"], answer:3,
   why:"Chlamydiae are obligate intracellular parasites and very small. Excess lipid describes mycobacteria, poor counterstain uptake describes Legionella, and a thin spiral body describes Treponema."},
  {id:"BAC1-029", m:"m2", area:"Selective toxicity", level:"concept",
   stem:"Which of these is a target unique to bacteria?",
   options:["Cytosolic 80S ribosome","Peptidoglycan","Nucleosome","Mitotic spindle"], answer:1,
   why:"Peptidoglycan is built only by bacteria, making it a classic selective target. The other three structures are features of human (eukaryotic) cells."},
  {id:"BAC1-030", m:"m2", area:"Selective toxicity", level:"application",
   stem:"Which bacterial enzyme do fluoroquinolones inhibit?",
   options:["Transpeptidase in the cell wall","Catalase in the cytoplasm","Coagulase on the cell surface","DNA gyrase (topoisomerase)"], answer:3,
   why:"Fluoroquinolones target the bacterial topoisomerases, including DNA gyrase. Transpeptidase is the beta-lactam target, while catalase and coagulase are not fluoroquinolone targets."},
  {id:"BAC1-031", m:"m2", area:"Selective toxicity", level:"integration",
   stem:"A drug blocks folate synthesis and spares human cells. Which fact explains this?",
   options:["Humans obtain folate from the diet","Humans build a peptidoglycan wall","Humans use 70S ribosomes in the cytosol","Humans store folate in mitochondria"], answer:0,
   why:"Bacteria must make their own folate, whereas humans take it in from the diet. Sulfonamides and trimethoprim exploit that difference."},
  {id:"BAC1-032", m:"m2", area:"Selective toxicity", level:"integration",
   stem:"Daptomycin and polymyxins act on which bacterial feature?",
   options:["Peptidoglycan cross-links within the cell wall","The 70S ribosome that synthesizes proteins","Folate synthesis enzymes inside the cell","Membranes that differ from human membranes"], answer:3,
   why:"Daptomycin and the polymyxins act on bacterial membranes, which are structurally distinct from human membranes."},

  /* ----- Module 3 ----- */
  {id:"BAC1-033", m:"m3", area:"Oxygen and intracellular growth", level:"concept",
   stem:"Which term describes bacteria that can use oxygen for growth but can also grow anaerobically?",
   options:["Obligate aerobe","Facultative anaerobe","Obligate anaerobe","Microaerophile"], answer:1,
   why:"Facultative anaerobes grow with or without oxygen, and many familiar clinical bacteria such as E. coli fall in this group."},
  {id:"BAC1-034", m:"m3", area:"Oxygen and intracellular growth", level:"application",
   stem:"In a tube culture, growth appears at the bottom, where oxygen is lowest. Which category fits?",
   options:["Obligate aerobe","Microaerophile","Facultative anaerobe","Obligate anaerobe"], answer:3,
   why:"Obligate anaerobes are inhibited or killed by oxygen, so they grow deep in the tube. An obligate aerobe would grow at the surface."},
  {id:"BAC1-035", m:"m3", area:"Oxygen and intracellular growth", level:"application",
   stem:"An organism grows evenly from the top to the bottom of a tube of medium, regardless of the oxygen level at each depth. Which category fits?",
   options:["Obligate anaerobe","Obligate aerobe","Aerotolerant anaerobe","Facultative anaerobe"], answer:2,
   why:"Aerotolerant anaerobes tolerate oxygen but do not use it for growth, so growth is even. A facultative anaerobe would be denser near the top."},
  {id:"BAC1-036", m:"m3", area:"Oxygen and intracellular growth", level:"concept",
   stem:"Which requirement is shared by Chlamydia, Rickettsia, Ehrlichia, and Anaplasma?",
   options:["Living host cells for growth","An oxygen-free atmosphere","A chitin-containing cell wall","Spore formation during growth"], answer:0,
   why:"These are obligate intracellular pathogens, which need living host cells to grow."},
  {id:"BAC1-037", m:"m3", area:"Endospores", level:"concept",
   stem:"Which genus is a spore-forming pathogen relevant to pharmacy practice?",
   options:["Staphylococcus","Escherichia","Neisseria","Clostridioides"], answer:3,
   why:"Clostridioides (for example C. difficile) and Bacillus are the key spore-forming genera for pharmacy practice. Staphylococcus, Escherichia, and Neisseria do not form spores."},
  {id:"BAC1-038", m:"m3", area:"Endospores", level:"application",
   stem:"Which hand hygiene method is required after caring for a patient with C. difficile infection?",
   options:["Alcohol-based hand rub","Hand rub followed by gloves","Soap-and-water washing","An antiseptic wipe"], answer:2,
   why:"Alcohol-based rubs do not kill spores. Soap-and-water washing removes them mechanically."},
  {id:"BAC1-039", m:"m3", area:"Endospores", level:"integration",
   stem:"Why can spores persist on hospital surfaces for years?",
   options:["Rapid multiplication while on dry surfaces","Continuous secretion of toxin into the environment","Firm attachment to surfaces through pili","Resistance to heat, drying, and many disinfectants"], answer:3,
   why:"Endospores are dormant and extremely resistant, so they persist in the environment and promote transmission through contaminated surfaces and hands."},
  {id:"BAC1-040", m:"m3", area:"Gene transfer", level:"concept",
   stem:"Which process depends on a bacteriophage?",
   options:["Conjugation","Transformation","Transduction","Binary fission"], answer:2,
   why:"Transduction is DNA transfer mediated by a bacteriophage, a virus that infects bacteria."},
  {id:"BAC1-041", m:"m3", area:"Gene transfer", level:"application",
   stem:"A copy of a plasmid moves between two bacteria joined by a pilus. Which mechanism is at work?",
   options:["Transformation","Transduction","Transposition","Conjugation"], answer:3,
   why:"Conjugation is direct cell-to-cell transfer through physical contact, bridged by a pilus, and it moves plasmids."},
  {id:"BAC1-042", m:"m3", area:"Gene transfer", level:"concept",
   stem:"In conjugation, which structure carries resistance genes from donor to recipient?",
   options:["Ribosome","Plasmid","Capsule","Flagellum"], answer:1,
   why:"DNA is transferred in circular constructs called plasmids, which can encode resistance, virulence, metabolic, and transfer traits."},
  {id:"BAC1-043", m:"m3", area:"Gene transfer", level:"integration",
   stem:"A resistance gene spreads to a neighboring bacterium without cell contact or a virus. Which mechanism fits?",
   options:["Conjugation","Binary fission","Transduction","Transformation"], answer:3,
   why:"Transformation is uptake of naked DNA from the environment, so it requires neither contact with a donor nor a phage."},
  {id:"BAC1-044", m:"m3", area:"Antimicrobial resistance", level:"concept",
   stem:"Which type of resistance is an inherent property of the organism?",
   options:["Acquired resistance","Intrinsic resistance","Conjugative resistance","Mutational resistance"], answer:1,
   why:"Intrinsic resistance is built into the organism, for example the outer-membrane impermeability of Gram-negative bacteria. Acquired resistance comes from mutation or horizontal gene transfer."},
  {id:"BAC1-045", m:"m3", area:"Antimicrobial resistance", level:"application",
   stem:"An infection recurs after a drug removes susceptible pathogens and normal flora, leaving resistant cells. Which process best explains the recurrence?",
   options:["Induction of mutations by the drug","Conversion of the pathogen to a spore","Loss of the outer membrane","Selection of a resistant subpopulation"], answer:3,
   why:"The drug removes competitors, so the resistant subpopulation that survived can proliferate. The drug selects resistance; it does not create it."},
  {id:"BAC1-046", m:"m3", area:"Antimicrobial resistance", level:"application",
   stem:"Acquired resistance can arise through which routes?",
   options:["Capsule formation or pilus loss","Spore formation or motility","Mutation or horizontal gene transfer","Toxin release or opsonization"], answer:2,
   why:"Acquired resistance is gained through mutation or through horizontal gene transfer by transformation, transduction, or conjugation."},
  {id:"BAC1-047", m:"m3", area:"Antimicrobial resistance", level:"integration",
   stem:"Which sequence describes how resistance spreads within a hospital unit?",
   options:["Drug selects resistant cells, they proliferate, and they pass genes on by conjugation","Drug creates resistance genes, cells lyse, and DNA is taken up by transformation","Cells form spores, spores germinate, and plasmids are destroyed","A phage kills the resistant cells, and susceptible cells multiply"], answer:0,
   why:"Exposure selects resistant survivors, which multiply without competition and can then transfer resistance genes to other bacteria, for example by conjugation."},

  /* ----- Module 4 ----- */
  {id:"BAC1-048", m:"m4", area:"Microbiome and colonization resistance", level:"concept",
   stem:"Which contribution to host health comes from resident gut bacteria?",
   options:["Secreting collagenase to loosen the gut wall","Forming endospores to protect the intestine","Producing exotoxins that prime immunity","Digesting plant fiber into short-chain fatty acids"], answer:3,
   why:"Gut bacteria digest otherwise-indigestible plant fibers into short-chain fatty acids that intestinal cells use, and they synthesize vitamin K and some B vitamins."},
  {id:"BAC1-049", m:"m4", area:"Microbiome and colonization resistance", level:"concept",
   stem:"Which product of resident bacteria directly inhibits competing bacteria?",
   options:["Coagulase","Leukocidins","Bacteriocins","Toxoids"], answer:2,
   why:"Bacteriocins are antimicrobial peptides made by some resident bacteria that inhibit competitors, one of the mechanisms of colonization resistance."},
  {id:"BAC1-050", m:"m4", area:"Microbiome and colonization resistance", level:"application",
   stem:"A patient develops C. difficile diarrhea after a course of broad-spectrum antibiotics. Which explanation fits best?",
   options:["Acquisition of a capsule by resident bacteria","Excess vitamin K from resident bacteria","Transmission by an arthropod vector","Loss of colonization resistance in the gut"], answer:3,
   why:"Broad-spectrum antibiotics deplete the resident microbiota, which reduces competition for nutrients and attachment sites and lets a pathogen establish itself."},
  {id:"BAC1-051", m:"m4", area:"Microbiome and colonization resistance", level:"application",
   stem:"Organisms are detected in healthy bladder urine. Which statement fits?",
   options:["The finding confirms infection, so treatment should begin immediately","The bladder is low in biomass, so detection alone leaves infection unproven","Urine from a healthy bladder is sterile, so the finding is a lab error","The bladder holds as many microbes as the colon, so growth is expected"], answer:1,
   why:"Healthy bladder urine and the lower airways are low-biomass environments rather than sterile ones, so detecting organisms there does not by itself establish infection."},
  {id:"BAC1-052", m:"m4", area:"Colonization and infection", level:"concept",
   stem:"Which term describes an organism that has invaded host tissue and caused a host response, with or without symptoms?",
   options:["Colonization","Contamination","Infection","Disease"], answer:2,
   why:"Infection means the organism invaded tissue and triggered a host response, and it can occur without symptomatic disease."},
  {id:"BAC1-053", m:"m4", area:"Colonization and infection", level:"concept",
   stem:"Which term describes symptomatic illness resulting from infection?",
   options:["Colonization","Contamination","Latent infection","Disease"], answer:3,
   why:"Disease is the symptomatic illness that results from infection. A latent infection is dormant and may be reactivated later."},
  {id:"BAC1-054", m:"m4", area:"Colonization and infection", level:"application",
   stem:"A urine culture from an asymptomatic patient with a chronic catheter grows E. coli. Which interpretation fits?",
   options:["Disease, so treatment should start immediately","Contamination from an inanimate object","A latent infection awaiting reactivation","Colonization, so symptoms should guide treatment"], answer:3,
   why:"Asymptomatic bacteriuria represents colonization rather than infection, so a positive culture alone does not justify an antibiotic."},
  {id:"BAC1-055", m:"m4", area:"Colonization and infection", level:"application",
   stem:"A gut commensal enters the bloodstream after abdominal surgery and causes sepsis. What does this illustrate?",
   options:["A zoonosis acquired from an animal reservoir","An obligate intracellular pathogen invading cells","Contamination introduced during specimen collection","A resident microbe causing disease at a new site"], answer:3,
   why:"Resident microbiota can act as potential pathogens depending on body site and host conditions, so a commensal introduced to a new site can cause disease there."},
  {id:"BAC1-056", m:"m4", area:"Transmission", level:"concept",
   stem:"Which term describes person-to-person spread that occurs without a parent-to-child link?",
   options:["Vertical transmission","Horizontal transmission","Zoonotic transmission","Vector transmission"], answer:1,
   why:"Horizontal transmission is spread from person to person other than from mother to offspring. Vertical transmission is mother to child."},
  {id:"BAC1-057", m:"m4", area:"Transmission", level:"application",
   stem:"A tick carries Borrelia from deer to a hiker. Which term applies to the tick?",
   options:["Fomite","Reservoir","Vector","Source"], answer:2,
   why:"A vector is a living organism, usually an arthropod, that transmits an infectious agent. A fomite is an inanimate object."},
  {id:"BAC1-058", m:"m4", area:"Transmission", level:"application",
   stem:"Brucella is maintained in cattle and infects a farmer. Which term describes this kind of disease?",
   options:["Latent infection","Fomite-borne disease","Vertical infection","Zoonosis"], answer:3,
   why:"Zoonoses are diseases that use animals as reservoirs."},
  {id:"BAC1-059", m:"m4", area:"Virulence and immune evasion", level:"concept",
   stem:"Which statement distinguishes virulence from pathogenicity?",
   options:["Virulence is a yes-or-no ability to cause disease","Virulence is the degree of the ability to cause disease","Virulence is the rate of transmission between hosts","Virulence is the level of resistance to antibiotics"], answer:1,
   why:"Pathogenicity is the ability to cause disease, and virulence is the degree of that ability. The two are related but distinct."},
  {id:"BAC1-060", m:"m4", area:"Virulence and immune evasion", level:"application",
   stem:"Which enzyme eases spread through subcutaneous tissue by degrading hyaluronic acid?",
   options:["Coagulase","IgA protease","Catalase","Hyaluronidase"], answer:3,
   why:"Hyaluronidase degrades hyaluronic acid (and collagenase degrades collagen), which helps bacteria spread through tissue."},
  {id:"BAC1-061", m:"m4", area:"Virulence and immune evasion", level:"application",
   stem:"The S. pyogenes M protein and S. aureus protein A help these bacteria by which action?",
   options:["Blunting complement activation and antibody binding","Digesting collagen to spread through connective tissue","Forming endospores that persist on dry surfaces","Transferring plasmids to neighboring bacteria"], answer:0,
   why:"M protein and protein A interfere with complement activation and antibody binding, which blunts opsonization and phagocytosis."},
  {id:"BAC1-062", m:"m4", area:"Virulence and immune evasion", level:"integration",
   stem:"Which combination best supports bacterial persistence on an implanted device?",
   options:["Rapid spore germination and lysis","Adherence followed by biofilm formation","Endotoxin release and cell swelling","Loss of the pili and the capsule"], answer:1,
   why:"Adherence lets bacteria attach to the device, and the biofilm matrix then protects the community and reduces antibiotic penetration."},
  {id:"BAC1-063", m:"m4", area:"Toxins and immunopathogenesis", level:"concept",
   stem:"Which feature distinguishes an exotoxin from an endotoxin?",
   options:["Exotoxins are LPS; endotoxin is a secreted polypeptide","Exotoxins come from Gram-negative bacteria; endotoxin comes from Gram-positive bacteria","Exotoxins are secreted polypeptides; endotoxin is LPS in the outer membrane","Exotoxins are spore proteins; endotoxin is a capsule polysaccharide"], answer:2,
   why:"Exotoxins are secreted polypeptides made by Gram-positive and Gram-negative bacteria. Endotoxin is the lipopolysaccharide of the Gram-negative outer membrane."},
  {id:"BAC1-064", m:"m4", area:"Toxins and immunopathogenesis", level:"application",
   stem:"A patient with Gram-negative sepsis develops fever and low blood pressure. Which bacterial component is the major driver?",
   options:["Teichoic acid","Diphtheria toxin","Protein A","Lipid A of LPS"], answer:3,
   why:"Lipid A is the major inflammatory component of LPS. Although endotoxin is weaker molecule for molecule than exotoxins, it can trigger fever, hypotension, and shock."},
  {id:"BAC1-065", m:"m4", area:"Toxins and immunopathogenesis", level:"integration",
   stem:"Tetanus and botulism are toxin-mediated with little tissue invasion. Which preventive approach follows from this?",
   options:["Toxoid vaccines made by treating exotoxin with formaldehyde","Alcohol-based hand rub used before patient contact","Vaccines made from purified LPS of the outer membrane","Sporicidal room cleaning after patient discharge"], answer:0,
   why:"Because the disease is caused by a secreted exotoxin, vaccination targets the toxin. Formaldehyde converts exotoxins to toxoids, which are used in vaccines."},

  /* ----- Module 5 ----- */
  {id:"BAC1-066", m:"m5", area:"Diagnostic sequence", level:"concept",
   stem:"Which test type is used when culture or microscopy is difficult or slow?",
   options:["Susceptibility testing of the isolate","Molecular (NAAT) or antigen testing","Repeat Gram staining of the specimen","Endospore staining of the specimen"], answer:1,
   why:"Molecular tests such as NAAT, and antigen tests, are used when culture or microscopy is difficult or slow."},
  {id:"BAC1-067", m:"m5", area:"Diagnostic sequence", level:"concept",
   stem:"In the diagnostic sequence, which step follows identification of the isolate?",
   options:["Specimen collection","Gram staining","Culture","Susceptibility testing"], answer:3,
   why:"After the isolate is identified, susceptibility testing determines which antimicrobials are likely to work, and clinical interpretation follows."},
  {id:"BAC1-068", m:"m5", area:"Diagnostic sequence", level:"application",
   stem:"A blood culture bottle shows Gram-positive cocci in clusters. Which statement is supported by this result?",
   options:["The species is confirmed as Staphylococcus aureus and can be reported","The isolate is confirmed as the cause of the patient’s infection","The isolate is susceptible to standard dosing of common drugs","Shape and Gram reaction are known; species and susceptibility remain unknown"], answer:3,
   why:"Microscopy reports shape, arrangement, and Gram reaction. Identification, susceptibility, and clinical significance come from later steps."},
  {id:"BAC1-069", m:"m5", area:"Diagnostic sequence", level:"integration",
   stem:"Which order of steps reflects the diagnostic sequence?",
   options:["Specimen quality, Gram stain, culture or NAAT, identification, susceptibility, clinical interpretation","Susceptibility, identification, Gram stain, specimen quality, culture, clinical interpretation","Gram stain, specimen quality, identification, culture, clinical interpretation, susceptibility","Culture, specimen quality, susceptibility, Gram stain, identification, clinical interpretation"], answer:0,
   why:"The sequence starts with specimen quality and ends with interpretation of every result alongside the clinical picture."},
  {id:"BAC1-070", m:"m5", area:"Interpreting cultures", level:"application",
   stem:"Two blood cultures from a hospitalized patient with an implanted catheter both grow S. epidermidis. Which interpretation fits best?",
   options:["Skin contamination of both specimens","Probable true catheter-associated bacteremia","Colonization of the bloodstream by skin flora","A specimen collected from the wrong site"], answer:1,
   why:"Growth in multiple bottles argues against contamination, and an implanted catheter is a route for skin organisms. Together they point to a true catheter-associated bloodstream infection."},
  {id:"BAC1-071", m:"m5", area:"Interpreting cultures", level:"application",
   stem:"Sputum from a mildly ill outpatient grows a few colonies of S. pneumoniae. Which interpretation fits best?",
   options:["Definite pneumonia that requires antibiotics","A laboratory error in reading the culture plate","A true pathogen, since sputum comes from a sterile site","Likely upper-airway colonization, read with symptoms"], answer:3,
   why:"Sputum passes through the upper airway, which harbors resident organisms, so a few colonies should be interpreted with symptoms rather than treated on culture alone."},
  {id:"BAC1-072", m:"m5", area:"Interpreting cultures", level:"application",
   stem:"Stool from a patient with diarrhea after antibiotics is toxin-positive for C. difficile. Which interpretation fits?",
   options:["Colonization by a harmless commensal of the colon","Contamination of the sample during collection","A normal finding in the stool of healthy adults","Consistent with C. difficile infection in context"], answer:3,
   why:"A toxin-positive result in a patient with post-antibiotic diarrhea is consistent with C. difficile infection. The clinical context supports the result."},
  {id:"BAC1-073", m:"m5", area:"Interpreting cultures", level:"integration",
   stem:"Which statement best summarizes the pharmacist’s lesson from positive laboratory results?",
   options:["Detection establishes infection and calls for an antibiotic","Detection must be read with the clinical picture before treating","Detection from a non-sterile site is a laboratory error","Detection predicts susceptibility to standard therapy"], answer:1,
   why:"Organism detection is not the same as infection, and neither is an automatic indication for an antibiotic. Results have to be read alongside symptoms, specimen source, and history."},
  {id:"BAC1-074", m:"m5", area:"Susceptibility testing", level:"concept",
   stem:"Which report category means an organism is unlikely to respond even at maximal safe dosing?",
   options:["Susceptible","Resistant","Intermediate","Tolerant"], answer:1,
   why:"Resistant (R) means the organism is unlikely to respond even at maximal safe dosing."},
  {id:"BAC1-075", m:"m5", area:"Susceptibility testing", level:"concept",
   stem:"Which report category means a response is possible at higher dosing or where the drug concentrates at the infection site?",
   options:["Susceptible (S)","Intermediate (I)","Resistant (R)"], answer:1,
   why:"Intermediate, also called increased exposure, means the organism may respond at higher dosing or with drug concentrated at the infection site."},
  {id:"BAC1-076", m:"m5", area:"Susceptibility testing", level:"application",
   stem:"A biofilm-associated prosthetic joint infection persists although the isolate tests susceptible. Which limitation of MIC testing best explains this?",
   options:["Drug penetration and biofilm structure are absent from the test tube","The MIC scale scores spore-forming organisms as susceptible by default","Test tubes select for resistance mutations during the overnight incubation","Susceptibility reports describe the patient instead of the organism"], answer:0,
   why:"MIC results describe the organism in a test tube. They do not account for biofilms, source control, or how much drug reaches the infection site."},
  {id:"BAC1-077", m:"m5", area:"Susceptibility testing", level:"integration",
   stem:"Which information should be combined with an MIC report to guide therapy?",
   options:["The number of pili displayed by the isolate","The infection site and how well the drug reaches it","The Gram-stain color of the smear on its own","The number of plasmids carried by the isolate"], answer:1,
   why:"An MIC describes the organism in the laboratory. The infection site, drug penetration, biofilm presence, source control, and patient factors all decide whether the drug will work."}
];
